# Generated by Django 5.2.5 on 2025-09-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='servico',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
